import type { User, Project, Task, Milestone, ActivityItem } from '../types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Alex Johnson',
    email: 'alex.johnson@company.com',
    avatar: 'AJ',
    role: 'admin',
    avatarColor: '#6366f1',
  },
  {
    id: 'u2',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    avatar: 'SC',
    role: 'manager',
    avatarColor: '#8b5cf6',
  },
  {
    id: 'u3',
    name: 'Marcus Rivera',
    email: 'marcus.rivera@company.com',
    avatar: 'MR',
    role: 'developer',
    avatarColor: '#06b6d4',
  },
  {
    id: 'u4',
    name: 'Emily Watson',
    email: 'emily.watson@company.com',
    avatar: 'EW',
    role: 'designer',
    avatarColor: '#f59e0b',
  },
  {
    id: 'u5',
    name: 'David Park',
    email: 'david.park@company.com',
    avatar: 'DP',
    role: 'developer',
    avatarColor: '#10b981',
  },
  {
    id: 'u6',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    avatar: 'LT',
    role: 'tester',
    avatarColor: '#ef4444',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern UI/UX and improved performance metrics.',
    status: 'active',
    color: '#6366f1',
    startDate: '2026-03-01',
    endDate: '2026-06-30',
    memberIds: ['u1', 'u2', 'u3', 'u4'],
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-10T14:30:00Z',
  },
  {
    id: 'p2',
    name: 'Mobile App v2.0',
    description: 'Next major version of the mobile application featuring new features and performance improvements.',
    status: 'active',
    color: '#8b5cf6',
    startDate: '2026-02-15',
    endDate: '2026-07-31',
    memberIds: ['u1', 'u3', 'u5', 'u6'],
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-05-12T11:00:00Z',
  },
  {
    id: 'p3',
    name: 'API Integration',
    description: 'Integrate third-party APIs including payment gateway, analytics, and CRM systems.',
    status: 'planning',
    color: '#06b6d4',
    startDate: '2026-05-01',
    endDate: '2026-08-15',
    memberIds: ['u2', 'u3', 'u5'],
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-14T16:00:00Z',
  },
  {
    id: 'p4',
    name: 'Data Analytics Dashboard',
    description: 'Build a comprehensive analytics dashboard for business intelligence and reporting.',
    status: 'completed',
    color: '#10b981',
    startDate: '2025-11-01',
    endDate: '2026-02-28',
    memberIds: ['u1', 'u2', 'u4', 'u6'],
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
];

export const mockTasks: Task[] = [
  // Website Redesign tasks
  {
    id: 't1',
    projectId: 'p1',
    title: 'Design homepage wireframes',
    description: 'Create detailed wireframes for the new homepage including hero section, features, and CTA.',
    status: 'done',
    priority: 'high',
    assigneeId: 'u4',
    dueDate: '2026-03-20',
    tags: ['design', 'wireframe'],
    subtasks: [
      { id: 'st1', title: 'Research competitor sites', completed: true },
      { id: 'st2', title: 'Create low-fi mockups', completed: true },
      { id: 'st3', title: 'Get stakeholder approval', completed: true },
    ],
    comments: [
      { id: 'c1', userId: 'u2', content: 'Great work on the wireframes! Really captures the vision.', createdAt: '2026-03-18T14:00:00Z' },
    ],
    estimatedHours: 16,
    loggedHours: 14,
    milestoneId: 'm1',
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-03-20T17:00:00Z',
  },
  {
    id: 't2',
    projectId: 'p1',
    title: 'Implement responsive navigation',
    description: 'Build the main navigation component with mobile hamburger menu and smooth animations.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u3',
    dueDate: '2026-05-25',
    tags: ['frontend', 'react'],
    subtasks: [
      { id: 'st4', title: 'Desktop navigation', completed: true },
      { id: 'st5', title: 'Mobile hamburger menu', completed: false },
      { id: 'st6', title: 'Accessibility audit', completed: false },
    ],
    comments: [],
    estimatedHours: 12,
    loggedHours: 8,
    milestoneId: 'm1',
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-05-15T11:00:00Z',
  },
  {
    id: 't3',
    projectId: 'p1',
    title: 'Setup CI/CD pipeline',
    description: 'Configure automated testing and deployment pipeline using GitHub Actions.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u3',
    dueDate: '2026-06-01',
    tags: ['devops', 'automation'],
    subtasks: [],
    comments: [],
    estimatedHours: 8,
    loggedHours: 0,
    milestoneId: 'm2',
    createdAt: '2026-04-01T09:00:00Z',
    updatedAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 't4',
    projectId: 'p1',
    title: 'Optimize page load performance',
    description: 'Achieve 90+ Lighthouse score through image optimization, lazy loading, and code splitting.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u3',
    dueDate: '2026-06-15',
    tags: ['performance', 'optimization'],
    subtasks: [
      { id: 'st7', title: 'Image compression', completed: false },
      { id: 'st8', title: 'Implement lazy loading', completed: false },
    ],
    comments: [],
    estimatedHours: 20,
    loggedHours: 0,
    milestoneId: 'm2',
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-05T09:00:00Z',
  },
  {
    id: 't5',
    projectId: 'p1',
    title: 'Content migration',
    description: 'Migrate all existing content from the old CMS to the new system with proper formatting.',
    status: 'in_review',
    priority: 'low',
    assigneeId: 'u2',
    dueDate: '2026-05-20',
    tags: ['content', 'migration'],
    subtasks: [
      { id: 'st9', title: 'Export old content', completed: true },
      { id: 'st10', title: 'Format for new CMS', completed: true },
      { id: 'st11', title: 'Review and QA', completed: false },
    ],
    comments: [
      { id: 'c2', userId: 'u4', content: 'Some images are missing alt text. Please fix before approval.', createdAt: '2026-05-14T10:00:00Z' },
    ],
    estimatedHours: 24,
    loggedHours: 20,
    milestoneId: 'm1',
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-05-14T10:00:00Z',
  },
  // Mobile App tasks
  {
    id: 't6',
    projectId: 'p2',
    title: 'Redesign onboarding flow',
    description: 'Create a smooth, engaging onboarding experience for new users with progressive disclosure.',
    status: 'done',
    priority: 'critical',
    assigneeId: 'u4',
    dueDate: '2026-04-15',
    tags: ['ux', 'onboarding'],
    subtasks: [
      { id: 'st12', title: 'User research', completed: true },
      { id: 'st13', title: 'Prototype', completed: true },
      { id: 'st14', title: 'User testing', completed: true },
    ],
    comments: [
      { id: 'c3', userId: 'u1', content: 'Excellent work. User testing shows 40% improvement in completion rate!', createdAt: '2026-04-16T09:00:00Z' },
    ],
    estimatedHours: 32,
    loggedHours: 35,
    milestoneId: 'm3',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-04-16T09:00:00Z',
  },
  {
    id: 't7',
    projectId: 'p2',
    title: 'Implement push notifications',
    description: 'Add FCM-based push notifications with user preference controls.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u5',
    dueDate: '2026-05-30',
    tags: ['backend', 'notifications'],
    subtasks: [
      { id: 'st15', title: 'FCM setup', completed: true },
      { id: 'st16', title: 'Notification templates', completed: false },
      { id: 'st17', title: 'User preferences UI', completed: false },
    ],
    comments: [],
    estimatedHours: 20,
    loggedHours: 10,
    milestoneId: 'm3',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-05-10T14:00:00Z',
  },
  {
    id: 't8',
    projectId: 'p2',
    title: 'Offline mode support',
    description: 'Implement local data caching and conflict resolution for offline functionality.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'u5',
    dueDate: '2026-06-30',
    tags: ['mobile', 'offline'],
    subtasks: [],
    comments: [],
    estimatedHours: 40,
    loggedHours: 0,
    milestoneId: 'm4',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 't9',
    projectId: 'p2',
    title: 'Performance profiling and optimization',
    description: 'Profile app performance and fix memory leaks and rendering bottlenecks.',
    status: 'in_review',
    priority: 'medium',
    assigneeId: 'u6',
    dueDate: '2026-05-25',
    tags: ['performance', 'testing'],
    subtasks: [
      { id: 'st18', title: 'Performance baseline', completed: true },
      { id: 'st19', title: 'Fix render issues', completed: true },
      { id: 'st20', title: 'Write performance tests', completed: false },
    ],
    comments: [],
    estimatedHours: 16,
    loggedHours: 14,
    milestoneId: 'm3',
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-05-12T11:00:00Z',
  },
  // API Integration tasks
  {
    id: 't10',
    projectId: 'p3',
    title: 'Payment gateway integration',
    description: 'Integrate Stripe payment gateway with support for cards, wallets, and subscriptions.',
    status: 'todo',
    priority: 'critical',
    assigneeId: 'u3',
    dueDate: '2026-06-15',
    tags: ['payments', 'stripe'],
    subtasks: [
      { id: 'st21', title: 'Stripe SDK setup', completed: false },
      { id: 'st22', title: 'Payment flow implementation', completed: false },
      { id: 'st23', title: 'Webhook handlers', completed: false },
    ],
    comments: [],
    estimatedHours: 30,
    loggedHours: 0,
    milestoneId: 'm5',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 't11',
    projectId: 'p3',
    title: 'CRM data sync',
    description: 'Build bidirectional sync between our platform and Salesforce CRM.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u5',
    dueDate: '2026-07-01',
    tags: ['crm', 'integration'],
    subtasks: [],
    comments: [],
    estimatedHours: 25,
    loggedHours: 0,
    milestoneId: 'm5',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 't12',
    projectId: 'p3',
    title: 'Analytics event tracking',
    description: 'Implement comprehensive event tracking with Mixpanel for user behavior analytics.',
    status: 'in_progress',
    priority: 'medium',
    assigneeId: 'u2',
    dueDate: '2026-05-31',
    tags: ['analytics', 'tracking'],
    subtasks: [
      { id: 'st24', title: 'Define event taxonomy', completed: true },
      { id: 'st25', title: 'Implement tracking calls', completed: false },
    ],
    comments: [],
    estimatedHours: 18,
    loggedHours: 6,
    milestoneId: 'm5',
    createdAt: '2026-05-05T09:00:00Z',
    updatedAt: '2026-05-14T14:00:00Z',
  },
  // Analytics Dashboard tasks (completed project)
  {
    id: 't13',
    projectId: 'p4',
    title: 'Data pipeline setup',
    description: 'Configure ETL pipeline from multiple data sources.',
    status: 'done',
    priority: 'high',
    assigneeId: 'u3',
    dueDate: '2025-12-15',
    tags: ['data', 'pipeline'],
    subtasks: [],
    comments: [],
    estimatedHours: 40,
    loggedHours: 38,
    milestoneId: null,
    createdAt: '2025-11-05T09:00:00Z',
    updatedAt: '2025-12-15T17:00:00Z',
  },
  {
    id: 't14',
    projectId: 'p4',
    title: 'Dashboard UI implementation',
    description: 'Build the main dashboard UI with charts and data visualization.',
    status: 'done',
    priority: 'high',
    assigneeId: 'u4',
    dueDate: '2026-01-31',
    tags: ['frontend', 'charts'],
    subtasks: [],
    comments: [],
    estimatedHours: 60,
    loggedHours: 62,
    milestoneId: null,
    createdAt: '2025-11-15T09:00:00Z',
    updatedAt: '2026-02-01T17:00:00Z',
  },
  {
    id: 't15',
    projectId: 'p4',
    title: 'Report generation module',
    description: 'PDF and CSV export functionality for all dashboard reports.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'u5',
    dueDate: '2026-02-15',
    tags: ['reports', 'export'],
    subtasks: [],
    comments: [],
    estimatedHours: 24,
    loggedHours: 26,
    milestoneId: null,
    createdAt: '2025-12-01T09:00:00Z',
    updatedAt: '2026-02-16T10:00:00Z',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm1',
    projectId: 'p1',
    title: 'Design & Content Complete',
    description: 'All design assets and content ready for development.',
    dueDate: '2026-04-30',
    status: 'completed',
    taskIds: ['t1', 't5'],
  },
  {
    id: 'm2',
    projectId: 'p1',
    title: 'Development Complete',
    description: 'All frontend and backend code implemented and tested.',
    dueDate: '2026-06-15',
    status: 'in_progress',
    taskIds: ['t2', 't3', 't4'],
  },
  {
    id: 'm3',
    projectId: 'p2',
    title: 'Beta Release',
    description: 'Feature complete beta version ready for testing.',
    dueDate: '2026-05-31',
    status: 'in_progress',
    taskIds: ['t6', 't7', 't9'],
  },
  {
    id: 'm4',
    projectId: 'p2',
    title: 'Production Release',
    description: 'Full v2.0 release to all users.',
    dueDate: '2026-07-31',
    status: 'pending',
    taskIds: ['t8'],
  },
  {
    id: 'm5',
    projectId: 'p3',
    title: 'Phase 1 Integrations',
    description: 'Payment, CRM, and Analytics integrations complete.',
    dueDate: '2026-07-15',
    status: 'in_progress',
    taskIds: ['t10', 't11', 't12'],
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: 'a1',
    userId: 'u3',
    action: 'completed task',
    target: 'Design homepage wireframes',
    projectId: 'p1',
    taskId: 't1',
    createdAt: '2026-05-17T09:00:00Z',
  },
  {
    id: 'a2',
    userId: 'u4',
    action: 'updated',
    target: 'Mobile App v2.0',
    projectId: 'p2',
    createdAt: '2026-05-17T08:30:00Z',
  },
  {
    id: 'a3',
    userId: 'u2',
    action: 'commented on',
    target: 'Content migration',
    projectId: 'p1',
    taskId: 't5',
    createdAt: '2026-05-16T16:00:00Z',
  },
  {
    id: 'a4',
    userId: 'u5',
    action: 'started task',
    target: 'Implement push notifications',
    projectId: 'p2',
    taskId: 't7',
    createdAt: '2026-05-16T10:00:00Z',
  },
  {
    id: 'a5',
    userId: 'u1',
    action: 'created project',
    target: 'API Integration',
    projectId: 'p3',
    createdAt: '2026-05-15T14:00:00Z',
  },
  {
    id: 'a6',
    userId: 'u6',
    action: 'moved to review',
    target: 'Performance profiling and optimization',
    projectId: 'p2',
    taskId: 't9',
    createdAt: '2026-05-15T11:00:00Z',
  },
  {
    id: 'a7',
    userId: 'u2',
    action: 'added milestone',
    target: 'Phase 1 Integrations',
    projectId: 'p3',
    createdAt: '2026-05-14T15:00:00Z',
  },
  {
    id: 'a8',
    userId: 'u3',
    action: 'updated',
    target: 'Implement responsive navigation',
    projectId: 'p1',
    taskId: 't2',
    createdAt: '2026-05-14T09:30:00Z',
  },
];
